---
engines:
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths: 
  - "src/pygtk_chart/*"
  - "MANIFEST.in"
  - "src/OXM/images/**"
  - "src/OXM/images_map/*.png" 
